version: '3.5'

services:

  my-tests:
    build: .
    environment:
      - JEST_TEST_TIMEOUT=10000
      - UOL_URL=https://www.uol.com.br/
    # volumes:
    #   - ./__tests__:/app/__tests__
    #   - ./screenshots:/app/screenshots
    # command: sleep 99999
  
