version: '3.5'

services:

  my-tests:
    build: .
    environment:
      - JEST_TEST_TIMEOUT=10000
      - UOL_URL=https://uolhost.uol.com.br/
    volumes:
      - ./__tests__:/app/__tests__
    command: sleep 99999
  
